  version: '2'
  services:
    mysqldb:
      image: mysql:5.7.16
      volumes:
        - ./db/mysql:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
    oauth2-code:
      build: code/
      ports:
        - "6881:6881"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-code"
      #    env: "dev"
    oauth2-token:
      build: token/
      ports:
        - "6882:6882"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    oauth2-service:
      build: service/
      ports:
        - "6883:6883"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    oauth2-client:
      build: client/
      ports:
        - "6884:6884"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
    oauth2-user:
      build: user/
      ports:
        - "6885:6885"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-user"
      #    env: "dev"
    oauth2-key:
      build: key/
      ports:
        - "6886:6886"
      volumes:
        - ./db/mysql/config:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-key"
      #    env: "dev"
